---
title: "GSS data"
author: "Zijun Ye"
date: "05/12/2020"
output: pdf_document
---

```{r, warning=FALSE}
library(janitor)
library(tidyverse)
setwd("/Users/chuckyip/Desktop/FinalProject")

# Load the data dictionary and the raw data and correct the variable names
raw_data <- read_csv("AAIb6L2G.csv")
dict <- read_lines("gss_dict.txt", skip = 18) # skip is because of preamble content
# Now we need the labels because these are the actual responses that we need
labels_raw <- read_file("gss_labels.txt")


#### Set-up the dictionary ####
# What we want is a variable name and a variable definition
variable_descriptions <- as_tibble(dict) %>% 
  filter(value!="}") %>% 
  mutate(value = str_replace(value, ".+%[0-9].*f[ ]{2,}", "")) %>% 
  mutate(value = str_remove_all(value, "\"")) %>% 
  rename(variable_description = value) %>% 
  bind_cols(tibble(variable_name = colnames(raw_data)[-1]))
 
# Now we want a variable name and the possible values
labels_raw_tibble <- as_tibble(str_split(labels_raw, ";")[[1]]) %>% 
  filter(row_number()!=1) %>% 
  mutate(value = str_remove(value, "\nlabel define ")) %>% 
  mutate(value = str_replace(value, "[ ]{2,}", "XXX")) %>% 
  mutate(splits = str_split(value, "XXX")) %>% 
  rowwise() %>% 
  mutate(variable_name = splits[1], cases = splits[2]) %>% 
  mutate(cases = str_replace_all(cases, "\n [ ]{2,}", "")) %>%
  select(variable_name, cases) %>% 
  drop_na()

# Now we have the variable name and the different options e.g. age and 0-9, 10-19, etc.
labels_raw_tibble <- labels_raw_tibble %>% 
  mutate(splits = str_split(cases, "[ ]{0,}\"[ ]{0,}"))

# The function sets up the regex (I know, I know, but eh: https://xkcd.com/208/)
add_cw_text <- function(x, y){
  if(!is.na(as.numeric(x))){
    x_new <- paste0(y, "==", x,"~")
  }
  else{
    x_new <- paste0("\"",x,"\",")
  }
  return(x_new)
}

# The function will be in the row, but it'll get the job done
cw_statements <- labels_raw_tibble %>% 
  rowwise() %>% 
  mutate(splits_with_cw_text = list(modify(splits, add_cw_text, y = variable_name))) %>% 
  mutate(cw_statement = paste(splits_with_cw_text, collapse = "")) %>% 
  mutate(cw_statement = paste0("case_when(", cw_statement,"TRUE~\"NA\")")) %>% 
  mutate(cw_statement = str_replace(cw_statement, ",\"\",",",")) %>% 
  select(variable_name, cw_statement)
# So for every variable we now have a case_when() statement that will convert 
# from the number to the actual response.

# Just do some finally cleanup of the regex.
cw_statements <- 
  cw_statements %>% 
  mutate(variable_name = str_remove_all(variable_name, "\\r")) %>% 
  mutate(cw_statement = str_remove_all(cw_statement, "\\r"))
```


```{r, warning=FALSE}
#### Apply that dictionary to the raw data ####
# Pull out a bunch of variables and then apply the case when statement for the categorical variables
gss <- raw_data %>% 
  select(agedc,
         #6-9 missing
         sex,
         rlr_110,
         cow_10,
         chrinhdc,
         bpr_19,
         brthcan,
         # 96-99 missing
         hsdsizec,
         prv,
         famincg2,
         lanmt,
         agegr10,
         marstat,
         ehg3_01b
         ) %>% 
  mutate_at(vars(sex:brthcan), .funs = funs(ifelse(.>=6, NA, .))) %>% 
  mutate_at(vars(hsdsizec:ehg3_01b), .funs = funs(ifelse(.>=96, NA, .))) %>% 
  mutate_at(.vars = vars(sex:ehg3_01b),
            .funs = funs(eval(parse(text = cw_statements %>%
                                      filter(variable_name==deparse(substitute(.))) %>%
                                      select(cw_statement) %>%
                                      pull()))))
```

```{r}
# Fix the names
gss <- gss %>% 
  clean_names() %>% 
  rename(
    age=agedc,
    sex = sex,
    religion_importance=rlr_110,
    employment=cow_10,
    have_children=chrinhdc,
    citizenship = bpr_19,
    born_canada=brthcan,
    household_size = hsdsizec,
    province=prv,
    household_income=famincg2,
    mothertongue=lanmt,
    age_group = agegr10,
    marital = marstat,
    education = ehg3_01b) 
```

```{r}
# Clean up

# age + 2 (2017 - 2019), filter out age less than 18
# make it into age_group
gss$age <- gss$age + 2
gss <- gss %>% filter(gss$age >= 18)
gss <- gss %>% mutate(age_group = ifelse(age >= 18 & age <= 30, "18-30",
                                            ifelse(age > 30 & age <= 55, "30-55",
                                            ifelse(age > 55 & age <= 70, "55-70", "Above 70"))))

# religion_importance
gss <- gss %>% filter(religion_importance != "NA")

# employment
gss$employment <- ifelse(gss$employment %in% c("Employee", "Self-employed", "Working in a family business without pay"), "Employed", "Unemployed")

# have_children
gss$have_children <- ifelse(gss$have_children %in% c("Four or more xhildren", "One child", "Three children", "Two children"), "Yes", "No")

# born_canada
gss <- gss %>% filter(born_canada != "NA")
gss$born_canada <- ifelse(gss$born_canada == "Born in Canada", "Yes", "No")

# household_size
gss$household_size <- ifelse(gss$household_size %in% c("Four person household", "Five person household", "Six or more person household"), "Four or more person household", gss$household_size)

# province (lack of 3 provinces)

# household_income

# marital
gss <- gss %>% filter(marital != "NA")
gss$marital <- ifelse(gss$marital %in% c("Married", "Separated", "Widowed"), "Married", "Not Married")

# education
gss <- gss %>% filter(education != "NA")
gss$education <- ifelse(gss$education %in% c("High school diploma or a high school equivalency certificate","Less than high school diploma or its equivalent"), "Less than highschool diploma or equivalent", "More than highschool diploma")

# mothertongue
gss <- gss %>% filter(mothertongue != "NA")
gss$mothertongue <- ifelse(gss$mothertongue %in% 
                             c("English and non-official language",
                               "French and non-official language", 
                               "English, French and non-official language", 
                               "Multiple non-official languages", 
                               "English and French"),
                           "Multiple",
                    ifelse(gss$mothertongue == "Non-official languages", "Others", gss$mothertongue))
```


```{r}
# Select column after cleaning up
gss <- gss %>% 
  select(sex,
         religion_importance,
         employment,
         have_children,
         born_canada,
         household_size,
         province,
         household_income,
         age_group,
         marital,
         education,
         mothertongue)
write_csv(gss, "gss.csv")

# make gss into cells and export the new dataset
final_gss <- gss %>% group_by(sex, religion_importance, have_children, province, household_income, marital, education, mothertongue) %>% count(sex)

write_csv(final_gss, "final_gss.csv")
```




